[font]
normal = { family = "SauceCodePro Nerd Font Mono" }
size = 12

[keyboard]
bindings = [
  { key = "L", mods = "Control", action = "ClearHistory" },
]

[window]
dimensions = { columns = 120, lines = 40 }
dynamic_padding = true
dynamic_title = false
padding = { x = 4, y = 4 }
