[colors]
background = "#0b0e14"
foreground = "#bfbdb6"
selection-background = "#409fff"
selection-foreground = "#0b0e14"
cursor = "#e6b450"
black = "#11151c"
red = "#ea6c73"
green = "#7fd962"
yellow = "#f9af4f"
blue = "#53bdfa"
magenta = "#cda1fa"
cyan = "#90e1c6"
white = "#c7c7c7"
light_black = "#686868"
light_red = "#f07178"
light_green = "#aad94c"
light_yellow = "#ffb454"
light_blue = "#59c2ff"
light_magenta = "#d2a6ff"
light_cyan = "#95e6cb"
light_white = "#ffffff"
