[symlinks]
"nvim\\init.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\init.lua"
"nvim\\lsp\\jdtls.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lsp\\jdtls.lua"
"nvim\\lsp\\jsonls.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lsp\\jsonls.lua"
"nvim\\lsp\\lemminx.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lsp\\lemminx.lua"
"nvim\\lsp\\lua_ls.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lsp\\lua_ls.lua"
"nvim\\lsp\\luau_lsp.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lsp\\luau_lsp.lua"
"nvim\\lsp\\pyrefly.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lsp\\pyrefly.lua"
"nvim\\lsp\\ruff.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lsp\\ruff.lua"
"nvim\\lsp\\rust_analyzer.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lsp\\rust_analyzer.lua"
"nvim\\lsp\\ts_ls.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lsp\\ts_ls.lua"
"nvim\\lua\\autocmds.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lua\\autocmds.lua"
"nvim\\lua\\keymaps.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lua\\keymaps.lua"
"nvim\\lua\\lsp.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lua\\lsp.lua"
"nvim\\lua\\options.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lua\\options.lua"
"nvim\\lua\\plugins\\editing.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lua\\plugins\\editing.lua"
"nvim\\lua\\plugins\\git.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lua\\plugins\\git.lua"
"nvim\\lua\\plugins\\init.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lua\\plugins\\init.lua"
"nvim\\lua\\plugins\\installers.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lua\\plugins\\installers.lua"
"nvim\\lua\\plugins\\snacks.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lua\\plugins\\snacks.lua"
"nvim\\lua\\plugins\\visuals.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lua\\plugins\\visuals.lua"
"nvim\\lua\\plugins\\workflow.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lua\\plugins\\workflow.lua"
"nvim\\lua\\roblox.lua" = "C:\\Users\\ohirume/AppData/Local/nvim\\lua\\roblox.lua"
"nvim\\selene.toml" = "C:\\Users\\ohirume/AppData/Local/nvim\\selene.toml"
"nvim\\stylua.toml" = "C:\\Users\\ohirume/AppData/Local/nvim\\stylua.toml"

[templates]
