[rio.files]
rio = "~/AppData/Local/rio"

[alacritty.files]
alacritty = "~/AppData/Roaming/alacritty"

[powershell.files]
PowerShell = "~/Documents/PowerShell"

[yazi.files]
yazi = "~/AppData/Roaming/yazi/config"

[nvim.files]
nvim = "~/AppData/Local/nvim"
