[rio.files]
"rio.toml" = "~/AppData/Local/rio/config.toml"

[powershell.files]
PowerShell = "~/Documents/PowerShell"

[yazi.files]
yazi = "~/AppData/Roaming/yazi/config"

[nvim.files]
nvim = "~/AppData/Local/nvim"
