[glzr.files]
glazewm = "~/.glzr/glazewm"
zebar = { target = "~/.glzr/zebar", type = "template" }

[rio.files]
rio = "~/AppData/Local/rio"

[alacritty.files]
alacritty = "~/AppData/Roaming/alacritty"

[powershell.files]
PowerShell = "~/Documents/PowerShell"

[yazi.files]
yazi = "~/AppData/Roaming/yazi/config"

[nvim.files]
nvim = "~/AppData/Local/nvim"
