format = """[ ](bg:#a3aed2 fg:#a3aed2)\
$os\
[ ](bg:#a3aed2 fg:#a3aed2)\
[](bg:#769ff0 fg:#a3aed2)\
$directory\
[](fg:#769ff0 bg:#394260)\
$git_branch\
$git_status\
[](fg:#394260 bg:#212736)\
$conda\
[](fg:#1d2230)\
$time\
\n$character"""

[os]
style = "bg:#a3aed2 fg:#090c0c"
disabled = false

[os.symbols]
Windows = ""
Ubuntu = "󰕈"
SUSE = ""
Raspbian = "󰐿"
Mint = "󰣭"
Macos = "󰀵"
Manjaro = ""
Linux = "󰌽"
Gentoo = "󰣨"
Fedora = "󰣛"
Alpine = ""
Amazon = ""
Android = ""
Arch = "󰣇"
Artix = "󰣇"
CentOS = ""
Debian = "󰣚"
Redhat = "󱄛"
RedHatEnterprise = "󱄛"

[directory]
format = "[ $path ]($style)"
style = "fg:#e3e5e5 bg:#769ff0"
truncation_length = 3
truncation_symbol = "…/"

[git_branch]
symbol = ""
style = "bg:#394260"
format = "[[ $symbol $branch ](fg:#769ff0 bg:#394260)]($style)"

[git_status]
style = "bg:#394260"
format = "[[($all_status$ahead_behind )](fg:#769ff0 bg:#394260)]($style)"

[conda]
symbol = " "
style = "fg:#a0a9cb bg:#1d2230"
format = "[ $symbol$environment ]($style)"
ignore_base = false

[time]
disabled = false
time_format = "%R"
format = "[ $time ]($style)"

[character]
success_symbol = "[ ➜](bold green)"
error_symbol = "[ ➜](bold red)"
